title: Title of your CV site
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Oscar Carrillo"
job: "Automation Java Developer"

phone_number: +52 (1) 56-3030-0339
address: Puebla, Mexico
email: orcg@dr.com
linkedin_username: oscar-rene-carrillo
github_username: github

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: https://github.com/oscarrcg

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
