title: CV - Oscar Carrillo
profile_img: /assets/img/Oscar Carrillo.jpg
icon_img: /assets/img/icon.webp

name: "Oscar Carrillo"
job: "Automation Java Developer"

phone_number: +52 (1) 56-3030-0339
address: Puebla, Mexico
email: oscarrcg@gmail.com
linkedin_username: oscar-rene-carrillo
github_username: oscarrcg

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
